import { useEffect, useMemo, useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import { ArrowLeft, ArrowRight, Award, BarChart3, BookMarked, Brain, CalendarDays, Clock3, Crown, Flag, Flame, Gem, Lightbulb, ListChecks, LockKeyhole, MapPinned, Menu, Pause, ScrollText, Settings, ShieldCheck, Sparkles, Star, Swords, Target, Timer, UserRound } from "lucide-react";
import { Link, Navigate, Route, Routes, useLocation, useNavigate, useParams } from "react-router-dom";
import type { AnswerResult, Chapter, Level, LevelResult, PublicQuestion, SubmittedAnswer, WrongQuestion, ReviewItem } from "@expedition/shared";
import { api } from "./api";
import { expeditionWorlds, leaderboard } from "./mock-content";
import { AchievementBadge, AnswerExplanation, AppShell, BookOpen, ChapterPath, Check, Compass, EmptyState, ErrorState, KnowledgeDetailPanel, KnowledgeNode, LoadingSkeleton, OptionButton, ProgressBar, ProgressRing, QuestionCard, QuestCard, ReviewScheduleCard, Sparkles as SparkleIcon, Trophy, WorldIslandCard } from "./components/game-ui";
import { usePlayer } from "./store";
import { useAuth } from "./auth";
import { AuthDialog } from "./components/auth-dialog";
import { TurnstileWidget } from "./components/turnstile";
import { hasCompleteAnswer, QuestionRenderer } from "./components/question-renderer";

export function App() {
  const location = useLocation();
  const onboarded = usePlayer(state => state.onboarded);
  const initializeAuth = useAuth(state => state.init);
  useEffect(() => { void initializeAuth(); }, [initializeAuth]);
  return <div className="app"><AnimatePresence mode="wait"><motion.div key={location.pathname} initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0 }} transition={{ duration: 0.24 }}><Routes>
    <Route path="/" element={<Welcome />} />
    <Route path="/onboarding" element={<Onboarding />} />
    <Route path="/camp" element={onboarded ? <Camp /> : <Navigate to="/" replace />} />
    <Route path="/map" element={<WorldMap />} />
    <Route path="/world/:id" element={<WorldDetail />} />
    <Route path="/battle/:levelId" element={<Battle />} />
    <Route path="/result/:sessionId" element={<Result />} />
    <Route path="/review" element={<Review />} />
    <Route path="/graph" element={<Graph />} />
    <Route path="/graph/:knowledgeId" element={<Graph />} />
    <Route path="/profile" element={<Profile />} />
    <Route path="/account" element={<Account />} />
    <Route path="/store" element={<Store />} />
    <Route path="/leaderboard" element={<Leaderboard />} />
    <Route path="*" element={<Navigate to="/" replace />} />
  </Routes></motion.div></AnimatePresence><AuthDialog /></div>;
}

function Welcome() {
  const navigate = useNavigate(); const startGuest = useAuth(state => state.startGuest); const openDialog = useAuth(state => state.openDialog); const [captchaToken, setCaptchaToken] = useState<string>(); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  async function begin() { setBusy(true); setError(""); try { await startGuest(captchaToken); navigate("/onboarding"); } catch (reason) { setError(reason instanceof Error ? reason.message : "当前无法创建游客身份，请稍后重试"); } finally { setBusy(false); } }
  return <section className="welcome-screen"><div className="welcome-map-lines" /><div className="welcome-compass"><Compass /></div><p className="eyebrow">KNOWLEDGE EXPEDITION</p><h1>知识远征</h1><p className="welcome-slogan">探索知识，点亮世界</p><p className="welcome-copy">把零散知识，走成一张自己的地图。</p><TurnstileWidget onToken={setCaptchaToken} />{error && <p className="welcome-error" role="alert">{error}</p>}<button type="button" className="button primary welcome-cta" disabled={busy} onClick={begin}>{busy ? "正在开启…" : "开始我的远征"} <ArrowRight /></button><button type="button" className="welcome-return" onClick={() => openDialog("login")}>邮箱登录或注册</button><small>也可以不注册，先完整体验第一段旅程</small></section>;
}

function Onboarding() {
  const [step, setStep] = useState(0); const [goal, setGoal] = useState("文化通识积累"); const [minutes, setMinutes] = useState(15);
  const finish = usePlayer(state => state.finishOnboarding); const navigate = useNavigate();
  const goals = ["公务员考试", "学生知识巩固", "文化通识积累", "计算速度训练", "自由探索"];
  return <section className="onboarding-screen"><header><Link to="/" aria-label="返回欢迎页"><ArrowLeft /></Link><ProgressBar value={(step + 1) / 3 * 100} /></header><div className="onboarding-card">{step === 0 && <><p className="eyebrow">第一步 · 定下方向</p><h1>这次远征，你想收获什么？</h1><div className="choice-list">{goals.map(item => <button type="button" className={goal === item ? "selected" : ""} onClick={() => setGoal(item)} key={item}>{item}<Chevron /></button>)}</div></>}{step === 1 && <><p className="eyebrow">第二步 · 安排行程</p><h1>每天留多少时间给自己？</h1><div className="time-options">{[5, 15, 30].map(item => <button type="button" key={item} className={minutes === item ? "selected" : ""} onClick={() => setMinutes(item)}><strong>{item}</strong><span>分钟</span><small>{item === 5 ? "轻量" : item === 15 ? "标准" : "强化"}</small></button>)}</div></>}{step === 2 && <><span className="route-seal"><MapPinned /></span><p className="eyebrow">路线已生成</p><h1>从文化万象启程</h1><p className="lead">先用一组精短挑战认识你的节奏，再沿地图逐步点亮知识。</p><div className="route-preview"><span>推荐首站</span><b>成语中的人物与承诺</b><small>{minutes} 分钟 · 5 个知识点 · 1 次守关挑战</small></div></>}<button type="button" className="button primary" onClick={() => step < 2 ? setStep(step + 1) : (finish(goal, minutes), navigate("/camp"))}>{step < 2 ? "继续" : "进入营地"}<ArrowRight /></button></div></section>;
}

function Camp() {
  const player = usePlayer();
  return <AppShell title="知识远征" subtitle="探索知识，点亮世界" theme="camp"><div className="camp-scene"><div className="camp-mountain mountain-a" /><div className="camp-mountain mountain-b" /><div className="camp-content"><section className="camp-dashboard"><div className="quest-panel paper-panel"><div className="panel-heading"><div><p className="eyebrow">今日任务</p><h2>向前推进一小段</h2></div><CalendarDays /></div><QuestCard icon={<Check />} title="成语辨析" current={0} total={10} tone="gold" /><QuestCard icon={<Check />} title="公考常识" current={0} total={15} tone="green" /><QuestCard icon={<Brain />} title="到期复习" current={0} total={6} tone="violet" /><Link className="button primary task-cta" to="/battle/idiom-1">开始学习 <ArrowRight /></Link></div><div className="camp-side"><section className="mastery-panel paper-panel"><p className="eyebrow">我的掌握度</p><div className="mastery-main"><ProgressRing value={68} label="掌握度" /><div><b>超过 73% 的玩家</b><p>今天再获得 180 经验即可升级。</p><Link to="/profile" className="button outline">查看完整报告</Link></div></div></section><section className="achievement-panel paper-panel"><div><p className="eyebrow">连续学习天数</p><strong>{player.streak} 天</strong></div><div className="week-streak" aria-label="连续学习七天">{["一", "二", "三", "四", "五", "六", "日"].map((day, index) => <span className={index < 6 ? "done" : "today"} key={day}><small>{day}</small><Check /></span>)}</div></section></div></section><section className="achievement-strip"><div className="strip-title"><h2>本周成就</h2><Link to="/profile">查看全部 <ArrowRight /></Link></div><AchievementBadge icon={<Flame />} title="连胜 3 天" caption="学习不停步" /><AchievementBadge icon={<Trophy />} title="全对关卡" caption="精准判断" /><AchievementBadge icon={<Timer />} title="速算达人" caption="节奏正好" /></section><section className="continue-section"><div className="strip-title"><div><p className="eyebrow">继续远征</p><h2>选择下一段旅程</h2></div><Link to="/map">打开大地图 <MapPinned /></Link></div><div className="continue-worlds">{expeditionWorlds.filter(world => !world.locked).slice(0, 4).map((world, index) => <Link to={`/world/${world.id}`} className={`continue-world card-${world.visual} ${index === 0 ? "featured" : ""}`} key={world.id}><p>{index === 0 ? "探索成语" : "探索中"}</p><h3>{world.name}</h3><span>{world.subtitle}</span><ProgressBar value={world.progress} tone={index === 0 ? "gold" : "green"} /><small>{world.chapterLabel}</small>{index === 0 && <b>继续</b>}</Link>)}</div></section></div></div></AppShell>;
}

function WorldMap() {
  return <AppShell title="知识地图" subtitle="选择你的远征世界"><section className="paper-map"><header className="map-head"><div><p>古地图 · 知识疆域</p><span>已点亮 <b>23 / 120</b> <Star /></span></div><Link className="map-rank-link" to="/leaderboard"><Trophy /> 远征排行榜</Link></header><div className="map-rose">✦</div><div className="island-grid">{expeditionWorlds.map(world => <WorldIslandCard world={world} key={world.id} />)}</div></section></AppShell>;
}

function WorldDetail() {
  const { id = "culture" } = useParams(); const world = expeditionWorlds.find(item => item.id === id) ?? expeditionWorlds[1]!;
  const [chapter,setChapter]=useState<(Chapter&{levels:Level[]})|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
  useEffect(()=>{api.world(id).then(result=>{const chapterId=result.chapters[0]?.id;if(!chapterId)throw new Error("该世界的题库正在筹备");return api.chapter(chapterId);}).then(setChapter).catch(reason=>setError(reason instanceof Error?reason.message:"章节加载失败")).finally(()=>setLoading(false));},[id]);
  return <AppShell title={world.name} subtitle="章节远征路线"><section className="chapter-page"><header className={`chapter-hero hero-${world.visual}`}><Link to="/map" aria-label="返回知识地图"><ArrowLeft /></Link><div><p>第一章 · {world.name}</p><h2>{chapter?.name??"加载中"} · 公考知识训练</h2><span><Trophy /> {chapter?.knowledgeCount??0} 个知识点 <Gem /> {chapter?.questionCount??0} 道训练题 <Star /> {chapter?.levels.length??0} 个关卡</span></div></header>{loading?<LoadingSkeleton/>:error?<ErrorState title="章节暂时无法打开" description={error}/>:chapter&&<><div className="chapter-intro"><ScrollText/><div><b>远征提示</b><p>{chapter.intro} 通关后会保存星级、错题和复习计划。</p></div></div><ChapterPath levels={chapter.levels}/><aside className="boss-teaser"><Swords/><div><p className="eyebrow">章节 Boss</p><h2>{chapter.bossName}</h2><span>{chapter.bossDescription}</span></div><Link className="button outline" to="/review">查看复习营</Link></aside></>}</section></AppShell>;
}

function Battle() {
  const {levelId="idiom-1"}=useParams(); const worldId=levelId.startsWith("common-")?"common":levelId.startsWith("numbers-")?"numbers":"culture"; const navigate=useNavigate(); const [session,setSession]=useState(""); const [index,setIndex]=useState(0); const [total,setTotal]=useState(0); const [levelName,setLevelName]=useState(""); const [question,setQuestion]=useState<PublicQuestion|null>(null); const [selected,setSelected]=useState<SubmittedAnswer>(); const [feedback,setFeedback]=useState<AnswerResult|null>(null); const [hint,setHint]=useState(false); const [status,setStatus]=useState<"loading"|"answering"|"submitting"|"feedback"|"error">("loading"); const [error,setError]=useState(""); const [startedAt,setStartedAt]=useState(Date.now());
  useEffect(()=>{api.start(levelId).then(result=>{setSession(result.sessionId);setIndex(result.currentIndex);setTotal(result.level.questionCount);setLevelName(result.level.name);setQuestion(result.currentQuestion);setStartedAt(Date.now());setStatus("answering");}).catch(reason=>{setError(reason instanceof Error?reason.message:"关卡加载失败");setStatus("error");});},[levelId]);
  async function submit(){if(!question||!selected)return;setStatus("submitting");setError("");try{setFeedback(await api.answer(session,{questionId:question.questionId,answer:selected,timeSpentMs:Date.now()-startedAt,usedHint:hint}));setStatus("feedback");}catch(reason){setError(reason instanceof Error?reason.message:"提交失败，请重试");setStatus("answering");}}
  async function next(){if(!feedback)return;if(feedback.progress.current>=total){try{await api.complete(session);navigate(`/result/${session}`);}catch(reason){setError(reason instanceof Error?reason.message:"结算失败，请重试");}return;}setQuestion(feedback.nextQuestion??null);setIndex(feedback.progress.current);setSelected(undefined);setFeedback(null);setHint(false);setStartedAt(Date.now());setStatus("answering");}
  if(status==="loading")return <section className="battle-page"><LoadingSkeleton/></section>; if(status==="error")return <section className="battle-page"><ErrorState title="关卡无法开始" description={error}/><Link className="button outline" to={`/world/${worldId}`}>返回章节</Link></section>;
  return <section className="battle-page"><header className="battle-top"><button type="button" onClick={()=>navigate(`/world/${worldId}`)} aria-label="返回"><ArrowLeft/></button><div><b>{levelName}</b><span><Timer/> 正在计时</span></div><ProgressBar value={(index+1)/Math.max(1,total)*100} label={`第 ${index+1} 题，共 ${total} 题`}/><button type="button" aria-label="暂停"><Pause/></button></header>{error&&<div className="offline-note">{error}</div>}<div className="battle-layout"><div><QuestionCard question={question}>{question&&<QuestionRenderer question={question} answer={selected} disabled={Boolean(feedback)||status==="submitting"} onChange={setSelected}/>}</QuestionCard><div className="battle-tools"><button type="button" disabled={Boolean(feedback)} className={hint?"active":""} onClick={()=>setHint(true)}><Lightbulb/>{hint?"提示已使用":"使用提示"}</button><button type="button"><BookMarked/>收藏题目</button></div></div><div className="explanation-column">{feedback?<aside className={`answer-detail ${feedback.isCorrect?"correct":"wrong"}`}><h2>{feedback.isCorrect?"回答正确":"再辨析一下"}</h2><p>{feedback.explanation.summary}</p><h3>为什么</h3><p>{feedback.explanation.whyCorrect}</p>{!feedback.isCorrect&&<p>{feedback.explanation.whyUserAnswerWrong}</p>}{feedback.explanation.commonMistake&&<><h3>常见误区</h3><p>{feedback.explanation.commonMistake}</p></>}{feedback.explanation.memoryTip&&<p className="memory-tip">记忆提示：{feedback.explanation.memoryTip}</p>}<small>掌握度变化 {feedback.masteryDelta>0?"+":""}{feedback.masteryDelta} · 下次复习 {new Date(feedback.nextReviewAt).toLocaleString()}</small></aside>:<aside className="explanation-empty"><ScrollText/><h2>解析将在作答后展开</h2><p>答案由服务器判断；页面不会预先保存正确答案。</p></aside>}</div></div><footer className="battle-footer"><span>进度 {index+1} / {total}</span><button type="button" className="button primary" disabled={feedback?false:!question||!hasCompleteAnswer(question,selected)||status==="submitting"} onClick={feedback?next:submit}>{status==="submitting"?"正在判定…":feedback?(feedback.progress.current>=total?"查看战报":"下一题"):"确认答案"}<ArrowRight/></button></footer></section>;
}

function Result(){const {sessionId=""}=useParams();const [result,setResult]=useState<LevelResult|null>(null);const [error,setError]=useState("");useEffect(()=>{api.complete(sessionId).then(setResult).catch(reason=>setError(reason instanceof Error?reason.message:"战报加载失败"));},[sessionId]);if(error)return <section className="result-page"><ErrorState title="战报暂时无法打开" description={error}/></section>;if(!result)return <section className="result-page"><LoadingSkeleton/></section>;const worldId=result.levelId.startsWith("common-")?"common":result.levelId.startsWith("numbers-")?"numbers":"culture";return <section className="result-page"><span className="result-medal"><Award/></span><p className="eyebrow">{result.levelName} · 结算完成</p><h1>{result.stars>0?"远征节点已点亮":"尚未达到通关线"}</h1><div className="result-stars" aria-label={`${result.stars} 星`}>{[1,2,3].map(star=><Star key={star} className={star<=result.stars?"earned":""}/>)}</div><ProgressRing value={result.correctRate} label="正确率"/><div className="result-stats"><span><b>{result.score}</b>总分</span><span><b>+{result.xp}</b>经验</span><span><b>+{result.coins}</b>金币</span><span><b>{result.wrongCount}</b>新增错题</span></div>{result.weakKnowledge.length>0&&<div className="review-reminder"><Brain/><div><b>本关薄弱点</b><span>{result.weakKnowledge.join("、")}</span></div></div>}{result.chapterMastery!==undefined&&<div className="boss-report"><h2>章节掌握报告</h2><p>章节掌握度 {result.chapterMastery}% · 最强知识点 {result.strongestKnowledge??"继续探索"}</p><p>下一次复习：{result.nextReviewAt?new Date(result.nextReviewAt).toLocaleString():"暂无"}</p></div>}<div className="result-actions"><Link className="button outline" to="/review">复习本关错题</Link><Link className="button primary" to={`/world/${worldId}`}>{result.nextLevelId?"解锁下一关":"返回章节地图"}<ArrowRight/></Link></div></section>}

function Review(){const [wrongs,setWrongs]=useState<WrongQuestion[]>([]);const [reviews,setReviews]=useState<ReviewItem[]>([]);const [loading,setLoading]=useState(true);useEffect(()=>{Promise.all([api.wrongs(),api.reviews()]).then(([wrongRows,reviewRows])=>{setWrongs(wrongRows);setReviews(reviewRows.upcoming);}).finally(()=>setLoading(false));},[]);return <AppShell title="复习营" subtitle="把即将遗忘的知识重新点亮"><section className="review-page"><div className="review-tabs"><button className="active">错题与复习</button></div>{loading?<LoadingSkeleton/>:<><div className="schedule-row"><ReviewScheduleCard active label="当前错题" count={String(wrongs.length)}/><ReviewScheduleCard label="复习计划" count={String(reviews.length)}/></div><section className="review-primary paper-panel"><div><p className="eyebrow">记忆修复</p><h2>{wrongs.length?`${wrongs.length} 道错题等待巩固`:"当前没有错题"}</h2><p>{reviews.length?`最近一次复习：${new Date(reviews[0]!.dueAt).toLocaleString()}`:"完成关卡后，系统会按掌握度自动安排复习。"}</p></div><div className="review-orbit"><Brain/><span>间隔复习</span></div></section><section className="wrong-question-list paper-panel"><div className="panel-heading"><div><p className="eyebrow">错题本</p><h2>按最近答错排序</h2></div><ListChecks/></div>{wrongs.length?wrongs.map(item=><article key={item.questionId}><div><b>{item.knowledgeName}</b><p>累计答错 {item.wrongCount} 次</p></div><small>{new Date(item.lastWrongAt).toLocaleString()}</small></article>):<EmptyState title="还没有错题" description="从成语初章开始第一场远征吧。"/>}</section></>}</section></AppShell>}

function Graph() { return <AppShell title="知识图谱" subtitle="建立可回忆的知识关系"><section className="graph-page"><div className="knowledge-network"><div className="network-center"><span>战役</span><strong>赤壁之战</strong><small>208 年</small></div><KnowledgeNode icon={<UserRound />} label="人物" items={["曹操", "孙权", "刘备", "周瑜"]} /><KnowledgeNode icon={<MapPinned />} label="地点" items={["长江", "赤壁"]} /><KnowledgeNode icon={<ScrollText />} label="典故" items={["万事俱备", "只欠东风"]} /><KnowledgeNode icon={<BookOpen />} label="作品" items={["三国志", "三国演义", "赤壁赋"]} /><KnowledgeNode icon={<Flag />} label="影响" items={["三国鼎立", "形成"]} /></div><KnowledgeDetailPanel /></section></AppShell>; }

const profileStats = [{ value: "23", label: "总学习天数", Icon: CalendarDays }, { value: "186", label: "掌握知识点", Icon: Sparkles }, { value: "56", label: "完成关卡", Icon: Swords }, { value: "78%", label: "正确率", Icon: Target }];
function Profile() { const player = usePlayer(); const authMode = useAuth(state => state.mode); const openDialog = useAuth(state => state.openDialog); return <AppShell title="我的远征" subtitle="每一次学习，都在点亮自己的地图"><section className="profile-page"><div className="profile-hero paper-panel"><span className="profile-avatar">远</span><div><p>{authMode === "guest" ? "游客远征者 · 当前设备保存" : "永久远征者 · 可跨设备同步"}</p><h2>Lv.12</h2><ProgressBar value={65} tone="green" /><small>{player.xp} / 3600 经验</small></div>{authMode === "guest" ? <button type="button" onClick={() => openDialog("bind")}><ShieldCheck /> 保存进度</button> : <Link to="/account" className="profile-account-link"><Settings /> 账号设置</Link>}</div><div className="profile-stats-grid">{profileStats.map(({ value, label, Icon }) => <article className="paper-panel" key={label}><Icon /><b>{value}</b><span>{label}</span></article>)}</div><section className="study-report paper-panel"><div className="panel-heading"><div><p className="eyebrow">学习报告</p><h2>最近 7 天</h2></div><div className="report-tabs"><button className="active">近 7 天</button><button>近 30 天</button><button>全部</button></div></div><div className="report-bars">{[38, 60, 48, 78, 52, 92, 68].map((value, index) => <span key={index}><i style={{ height: `${value}%` }} /><small>周{["一", "二", "三", "四", "五", "六", "日"][index]}</small></span>)}</div></section><section className="badge-collection"><div className="strip-title"><h2>最近获得</h2><span>更多成就</span></div><AchievementBadge icon={<Flame />} title="连胜 5 天" caption="持续远征" /><AchievementBadge icon={<Crown />} title="博学多才" caption="掌握多门知识" /><AchievementBadge icon={<ShieldCheck />} title="历史达人" caption="完成历史路线" /></section></section></AppShell>; }

function Account() { const mode = useAuth(state => state.mode); const user = useAuth(state => state.user); const signOut = useAuth(state => state.signOut); const openDialog = useAuth(state => state.openDialog); const navigate = useNavigate(); return <AppShell title="账号与隐私" subtitle="你的远征记录由你掌控"><section className="account-page paper-panel"><p className="eyebrow">账号安全</p><h2>{mode === "permanent" ? user?.email ?? "已绑定邮箱" : "当前为游客模式"}</h2><p>{mode === "permanent" ? "此账号可在其他设备上恢复远征进度。" : "游客记录只保留在当前设备；绑定邮箱后可以跨设备同步。"}</p>{mode === "guest" && <button type="button" className="button primary" onClick={() => openDialog("bind")}>保存我的进度</button>}{mode === "permanent" && <button type="button" className="button outline" onClick={() => void signOut().then(() => navigate("/"))}>退出账号</button>}<hr /><h3>隐私与数据</h3><p>我们只使用学习进度、邮箱验证和必要的安全审计数据来提供服务；验证码和完整访问令牌不会被记录。若要删除账号与数据，请从已绑定邮箱发送请求至站点支持邮箱，核验身份后执行。</p><p className="account-links"><a href="/privacy.html">隐私政策</a><a href="/terms.html">用户协议</a></p></section></AppShell>; }

function Store() { const products = [["华夏纪年全解锁", "5 个章节 · 150 道题目", "建立清晰历史坐标", "永久解锁"], ["文化万象全解锁", "6 个章节 · 180 道题目", "适合文化通识积累", "永久解锁"], ["资料分析进阶包", "4 个专题 · 120 道题目", "提升速算与判断力", "永久解锁"], ["世界文明专题包", "4 个章节 · 100 道题目", "从城邦走向全球", "永久解锁"]] as const; return <AppShell title="远征商城" subtitle="在需要时，解锁更完整的探索路线"><section className="store-page"><header className="pass-card"><div><p className="eyebrow">远征通行证</p><h2>解锁全部知识世界</h2><p>获得完整学习路线、深度关系题和长期学习报告。学习仍然是主线，购买只是扩展边界。</p><button type="button" className="button gold">查看通行证 <ArrowRight /></button></div><span><Compass /></span></header><div className="product-grid">{products.map(([name, chapters, goal, permanent]) => <article className="product-card" key={name}><span className="product-mark"><ScrollText /></span><h2>{name}</h2><p>{chapters}</p><dl><div><dt>学习目标</dt><dd>{goal}</dd></div><div><dt>权益</dt><dd>{permanent}</dd></div></dl><footer><button type="button" className="button outline">查看详情</button></footer></article>)}</div></section></AppShell>; }

function Leaderboard() { return <AppShell title="远征排行榜" subtitle="轻激励，让长期学习更有回响"><section className="leaderboard-page"><div className="rank-tabs"><button className="active">总榜</button><button>本周</button><button>本世界</button></div><div className="podium">{leaderboard.slice(0, 3).map(([name, score, level], index) => <article className={`podium-${index + 1}`} key={name}><span>{index === 0 ? "2" : index === 1 ? "1" : "3"}</span><div className="rank-avatar">{name.slice(0, 1)}</div><b>{name}</b><small>{level}</small><strong><Star /> {score}</strong></article>)}</div><div className="rank-list paper-panel">{leaderboard.slice(3).map(([name, score, level], index) => <article key={name}><span>{index + 4}</span><div className="rank-avatar small">{name.slice(0, 1)}</div><b>{name}</b><small>{level}</small><strong>{score} <Star /></strong></article>)}</div></section></AppShell>; }

function Chevron() { return <ArrowRight size={18} />; }
