import Fastify from "fastify"; import cors from "@fastify/cors"; import helmet from "@fastify/helmet"; import rateLimit from "@fastify/rate-limit";
import {answerInput,startSessionInput,orderInput} from "@expedition/content-schema"; import {masteryDelta,nextReview} from "@expedition/game-engine";
import {levels,publicQuestion,questions,worlds} from "./data.js"; import {MemoryLearningStore} from "./store.js"; import {MockPaymentProvider} from "./payment.js";
const app=Fastify({logger:{redact:["req.headers.authorization","req.headers.cookie"]}}); const store=new MemoryLearningStore(); const payment=new MockPaymentProvider();
await app.register(helmet); await app.register(rateLimit,{max:120,timeWindow:"1 minute"}); await app.register(cors,{origin:(process.env.WEB_ORIGIN??"http://localhost:5173").split(",")});
app.setErrorHandler((error,request,reply)=>{request.log.error(error);const candidate=typeof error==="object"&&error!==null?error as {statusCode?:unknown}:{};const status=typeof candidate.statusCode==="number"?candidate.statusCode:500;const message=status<500&&error instanceof Error?error.message:"请求暂时无法完成";reply.status(status).send({error:{code:"REQUEST_FAILED",message,requestId:request.id}})});
app.get("/health",async()=>({ok:true,service:"knowledge-expedition-api"})); app.get("/api/v1/config",async()=>({appName:"知识远征",guestEnabled:true,mockMode:!process.env.SUPABASE_URL}));
app.post("/api/v1/auth/guest",async()=>({userId:`guest_${crypto.randomUUID()}`,token:`dev.${crypto.randomUUID()}`})); app.get("/api/v1/worlds",async()=>worlds); app.get("/api/v1/worlds/:id",async req=>({world:worlds.find(w=>w.id===(req.params as {id:string}).id),levels}));
app.post("/api/v1/sessions/start",async(req,reply)=>{const parsed=startSessionInput.safeParse(req.body);if(!parsed.success)return reply.code(400).send({error:{code:"INVALID_INPUT",message:"关卡无效",requestId:req.id}});return {sessionId:crypto.randomUUID(),levelId:parsed.data.levelId,total:questions.length,question:publicQuestion(questions[0]!)}});
app.get("/api/v1/sessions/:id/question",async req=>{const index=Number((req.query as {index?:string}).index??0);const q=questions[index];return q?publicQuestion(q):replyNotFound(req.id)});
app.post("/api/v1/sessions/:id/answer",async(req,reply)=>{const parsed=answerInput.safeParse(req.body);if(!parsed.success)return reply.code(400).send({error:{code:"INVALID_INPUT",message:"答案格式无效",requestId:req.id}});const q=questions.find(item=>item.id===parsed.data.questionId);if(!q)return reply.code(404).send(replyNotFound(req.id));const correct=q.answer===parsed.data.answer;const delta=masteryDelta({correct,difficulty:2,usedHint:parsed.data.usedHint,kind:q.kind,streak:0});const review=nextReview(new Date(),correct?"good":"again",Math.max(0,40+delta));await store.saveMastery("guest",{knowledgeId:q.knowledgeId,name:q.stem.slice(0,12),score:Math.max(0,40+delta),nextReviewAt:review.toISOString()});return {correct,explanation:q.explanation,masteryDelta:delta,nextReviewAt:review.toISOString()}});
app.get("/api/v1/mastery",async()=>store.getMastery("guest")); app.get("/api/v1/review/today",async()=>({due:await store.getMastery("guest")})); app.get("/api/v1/knowledge/:id/relations",async()=>({center:"赤壁之战",mastered:6,total:10,groups:[{label:"人物",items:["曹操","孙权","刘备","周瑜"]},{label:"时间与地点",items:["公元208年","长江赤壁"]},{label:"作品",items:["三国志","三国演义","赤壁赋"]}]}));
app.get("/api/v1/products",async()=>[{id:"history-full",name:"华夏纪年完整区",price:19.9,entitlementCode:"world.history"},{id:"pass-season",name:"远征季卡",price:29.9,entitlementCode:"pass.season"}]); app.post("/api/v1/orders",async(req,reply)=>{const parsed=orderInput.safeParse(req.body);if(!parsed.success)return reply.code(400).send({error:{code:"INVALID_INPUT",message:"商品无效",requestId:req.id}});const orderId=crypto.randomUUID();return {orderId,...await payment.createOrder({orderId,amount:1990})}});
function replyNotFound(requestId:string){return {error:{code:"NOT_FOUND",message:"内容不存在",requestId}}}
const port=Number(process.env.API_PORT??8787); app.listen({port,host:"0.0.0.0"}).catch(error=>{app.log.error(error);process.exit(1)});
