import type { LevelResult, Mastery, ReviewItem, SubmittedAnswer, WrongQuestion } from "@expedition/shared";

export interface StoredAttempt { questionId:string; knowledgeId:string; answer:SubmittedAnswer; isCorrect:boolean; timeSpentMs:number; usedHint:boolean; masteryDelta:number; createdAt:string }
export interface StoredSession { id:string; userId:string; levelId:string; status:"active"|"completed"; currentIndex:number; attempts:StoredAttempt[]; startedAt:string; completedAt?:string; result?:LevelResult }
type UserProgress={xp:number;coins:number;levels:Map<string,{stars:number;bestScore:number;attemptCount:number;completedAt:string}>;mastery:Map<string,Mastery>;wrongs:Map<string,WrongQuestion>;reviews:Map<string,ReviewItem>};
export type PlayerProfile={xp:number;coins:number;stars:number;completedLevels:number;masteryCount:number;totalQuestions:number;correctAnswers:number;correctRate:number;studyDays:number;streak:number;masteryRate:number;weeklyActivity:number[]};

export class MemoryLearningStore {
  private sessions=new Map<string,StoredSession>();
  private users=new Map<string,UserProgress>();
  private user(userId:string){let row=this.users.get(userId);if(!row){row={xp:0,coins:0,levels:new Map(),mastery:new Map(),wrongs:new Map(),reviews:new Map()};this.users.set(userId,row);}return row;}
  createSession(userId:string,levelId:string){const active=[...this.sessions.values()].find(row=>row.userId===userId&&row.levelId===levelId&&row.status==="active");if(active)return active;const session:StoredSession={id:crypto.randomUUID(),userId,levelId,status:"active",currentIndex:0,attempts:[],startedAt:new Date().toISOString()};this.sessions.set(session.id,session);return session;}
  getSession(id:string,userId:string){const row=this.sessions.get(id);return row?.userId===userId?row:null;}
  saveAttempt(session:StoredSession,attempt:StoredAttempt){const existing=session.attempts.find(row=>row.questionId===attempt.questionId);if(existing)return {attempt:existing,duplicate:true};session.attempts.push(attempt);session.currentIndex=session.attempts.length;return {attempt,duplicate:false};}
  complete(session:StoredSession,result:LevelResult){if(session.result)return session.result;session.status="completed";session.completedAt=new Date().toISOString();session.result=result;const user=this.user(session.userId);const prior=user.levels.get(session.levelId);user.levels.set(session.levelId,{stars:Math.max(prior?.stars??0,result.stars),bestScore:Math.max(prior?.bestScore??0,result.score),attemptCount:(prior?.attemptCount??0)+1,completedAt:session.completedAt});if(result.rewardGranted){user.xp+=result.xp;user.coins+=result.coins;}return result;}
  updateLearning(userId:string,input:{questionId:string;knowledgeId:string;knowledgeName:string;correct:boolean;answer:SubmittedAnswer;delta:number;nextReviewAt:string}){const user=this.user(userId);const current=user.mastery.get(input.knowledgeId);const score=Math.min(100,Math.max(0,(current?.score??0)+input.delta));user.mastery.set(input.knowledgeId,{knowledgeId:input.knowledgeId,name:input.knowledgeName,score,nextReviewAt:input.nextReviewAt});user.reviews.set(input.knowledgeId,{knowledgeId:input.knowledgeId,knowledgeName:input.knowledgeName,dueAt:input.nextReviewAt,reviewType:input.correct?"scheduled":"wrong_answer",sourceQuestionId:input.questionId});if(!input.correct){const wrong=user.wrongs.get(input.questionId);user.wrongs.set(input.questionId,{questionId:input.questionId,knowledgeId:input.knowledgeId,knowledgeName:input.knowledgeName,wrongCount:(wrong?.wrongCount??0)+1,lastWrongAt:new Date().toISOString(),status:"active"});}return score;}
  getProgress(userId:string){const user=this.user(userId);return {xp:user.xp,coins:user.coins,levels:user.levels};}
  getProfile(userId:string):PlayerProfile{const user=this.user(userId);const attempts=[...this.sessions.values()].filter(session=>session.userId===userId).flatMap(session=>session.attempts);const dayKey=(value:string)=>value.slice(0,10);const activity=new Map<string,number>();for(const attempt of attempts){const key=dayKey(attempt.createdAt);activity.set(key,(activity.get(key)??0)+1);}const now=new Date();const dayKeys=Array.from({length:7},(_,index)=>{const date=new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),now.getUTCDate()-6+index));return date.toISOString().slice(0,10);});let streak=0;for(let offset=0;;offset+=1){const date=new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),now.getUTCDate()-offset)).toISOString().slice(0,10);if(!(activity.get(date)??0))break;streak+=1;}const totalQuestions=attempts.length;const correctAnswers=attempts.filter(attempt=>attempt.isCorrect).length;const mastery=[...user.mastery.values()];return {xp:user.xp,coins:user.coins,stars:[...user.levels.values()].reduce((sum,level)=>sum+level.stars,0),completedLevels:user.levels.size,masteryCount:mastery.length,totalQuestions,correctAnswers,correctRate:totalQuestions?Math.round(correctAnswers/totalQuestions*100):0,studyDays:activity.size,streak,masteryRate:mastery.length?Math.round(mastery.reduce((sum,item)=>sum+item.score,0)/mastery.length):0,weeklyActivity:dayKeys.map(key=>activity.get(key)??0)};}
  getMastery(userId:string){return [...this.user(userId).mastery.values()];}
  getWrongs(userId:string){return [...this.user(userId).wrongs.values()].sort((a,b)=>b.lastWrongAt.localeCompare(a.lastWrongAt));}
  getReviews(userId:string){return [...this.user(userId).reviews.values()].sort((a,b)=>a.dueAt.localeCompare(b.dueAt));}
  exportUser(userId:string){const user=this.user(userId);return {version:1,progress:{xp:user.xp,coins:user.coins,levels:[...user.levels.entries()],mastery:[...user.mastery.entries()],wrongs:[...user.wrongs.entries()],reviews:[...user.reviews.entries()]},sessions:[...this.sessions.values()].filter(row=>row.userId===userId)};}
  importUser(userId:string,payload:unknown){if(!payload||typeof payload!=="object")return;const data=payload as {progress?:{xp?:number;coins?:number;levels?:Array<[string,{stars:number;bestScore:number;attemptCount:number;completedAt:string}]>;mastery?:Array<[string,Mastery]>;wrongs?:Array<[string,WrongQuestion]>;reviews?:Array<[string,ReviewItem]>};sessions?:StoredSession[]};const progress=data.progress;if(progress)this.users.set(userId,{xp:progress.xp??0,coins:progress.coins??0,levels:new Map(progress.levels??[]),mastery:new Map(progress.mastery??[]),wrongs:new Map(progress.wrongs??[]),reviews:new Map(progress.reviews??[])});for(const session of data.sessions??[])if(session.userId===userId)this.sessions.set(session.id,session);}
}
